### ISSUE TITLE
Placeholder Requests

### ISSUE THREAD

**Issue by th3lucas** [Sytm/simple-player-list#5]
I would love to have Placeholders for:

- Money (with Vault?)
- Rank/Group with LuckPerms
- InGame Time
- Player Ping

**Comment by Sytm** [comment]
I have added support for %ping%, because it is a somewhat popular use case (I guess) and not all too complicated.

For your other requests I have added the option to use the PlaceholderAPI instead, because I don't really want to manually integrate into other plugins because, well that is what PlaceholderAPI is for.
